backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow # Allows you to save drafts before publishing them
media_folder: static/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /images/uploads

# Make sure to change these before publishing
site_url: https://mallim-blog-uat.netlify.app/
display_url: https://mallim-blog-uat.netlify.app/
logo_url: https://via.placeholder.com/300x125?text=Example

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    preview_path: "blog/{{slug}}"
    fields:
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        required: false
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
